# N.B. with 2.1 the webhook notification no longer works
version: 2.0

jobs:
  build:
    working_directory: ~/implicitbox
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.8
    resource_class: medium
    steps:
      - run:
          name: Install dependencies
          command: |
                    apt update && apt install -y curl
                    curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
                    dpkg -i sbt-$SBT_VERSION.deb
                    rm sbt-$SBT_VERSION.deb
                    apt-get update
                    apt-get install -y sbt python-pip git build-essential clang libunwind-dev libgc-dev libre2-dev
                    curl -sL https://deb.nodesource.com/setup_10.x | bash -
                    apt-get install -y nodejs
                    apt-get clean && apt-get autoclean

      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: implicitbox-cache

      - run:
          name: Compile project for JVM / JS
          working_directory: ~/implicitbox
          command: cat /dev/null | sbt -J-Xmx3072m -J-XX:MaxMetaspaceSize=1024m +clean +test:compile +package

      - run:
          name: Run tests for JVM / JS
          working_directory: ~/implicitbox
          command: cat /dev/null | sbt -J-Xmx3072m -J-XX:MaxMetaspaceSize=1024m +test

      - run:
          name: Compile & Test project for Native
          working_directory: ~/implicitbox
          command: cat /dev/null | sbt -J-Xmx3072m -J-XX:MaxMetaspaceSize=1024m +implicitboxNative/clean +implicitboxNative/test +implicitboxNative/package

      - save_cache:
          key: implicitbox-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
